name: Push Spec

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v1
      - name: spec-push
        if: github.event.pull_request.merged == true
        uses: ./.github/actions/push-api-spec
        with:
          fortellis_username: "${{ secrets.FORTELLIS_USERNAME }}"
          fortellis_password: "${{ secrets.FORTELLIS_PASSWORD }}"
